# Generated by Django 5.0.6 on 2024-05-30 10:29

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminproxymodel_studentproxymodel_teacherproxymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Moderator',
                'verbose_name_plural': 'Moderators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.TeacherProxyManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='adminproxymodel',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='studentproxymodel',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacherproxymodel',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher'), ('moderator', 'Moderator')], default='student', max_length=20),
        ),
    ]
