# Generated by Django 5.0.6 on 2024-05-30 19:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_image_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
