# Generated by Django 5.0.6 on 2024-05-30 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_customgroup_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'student'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
